# Generated by Django 3.0.5 on 2020-12-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/images')),
                ('price', models.FloatField()),
                ('delprice', models.FloatField()),
                ('category', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
