# Generated by Django 3.0.5 on 2020-12-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
